### ISSUE TITLE
Indian Channel Requests

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#1934]
Consolidating 10 issues into 1. 
**Country of the channel:**
India

**Channel Name:**

- [ ] Sony Max #359 
- [ ] Disney Channel India #709 #854
- [ ] Hungama TV #709 #854 #1317
- [ ] SAB TV #1317
- [ ] Marvel HQ #854
- [ ] Cartoon Network India #854
- [ ] Star Jalsha #854
- [ ] TV9 Kannada #1273
- [ ] Colors kannada #1273
- [ ] Zee Kannada #1273
- [ ] Public Movies #1273
- [ ] Dighvijay News 24x7 #1273
- [ ] Raj Musix Kannada #1273
- [ ] News 18 Kannada #1273
- [ ] tatasky #1459
- [ ] airtel #1459
- [ ] jio #1459
- [ ] MTV India #1621
- [ ] ASIANET #1645
- [ ] ASIANET MOVIES #1645
- [ ] SURYA_TV #1645
- [ ] Sun tv #1715
- [ ] Vijay TV/Star Vijay #1715
- [ ] Colours Tamil #1715
- [ ] Zee tamil #1715
- [ ] Tamilone #1715

**Comment by LaneSh4d0w** [comment]
Will take a look once i'll be free.

**Comment by AS27-pro** [comment]
This link may help: https://github.com/AsianPingu/Tamil-IPTV

**Comment by Nzzyme** [comment]
@LaneSh4d0w  : When can we expect the channels to be up and running?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w  : When can we expect the channels to be up and running?

Did not have much time recently to investigate. I'll take a look now.

**Comment by LaneSh4d0w** [comment]
Testing : 9XM TV : https://m-c01-j2apps.s.llnwi.net/live_hd/0306.9XM.in.m3u8

**Comment by LaneSh4d0w** [comment]
They got lots of channels, new batch later.

**Comment by Sphinxroot** [comment]
#EXTINF:-1,Zee Mundo 
https://y5w8j4a9.ssl.hwcdn.net/mundohd/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee TV HD (SUB ENG USA)
https://y5w8j4a9.ssl.hwcdn.net/ztvhdusa/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee 24 Kalak
https://y5w8j4a9.ssl.hwcdn.net/kalak/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Action
https://y5w8j4a9.ssl.hwcdn.net/action/index.m3u8
#EXTINF:-1,Zee Anmol Cinema
https://y5w8j4a9.ssl.hwcdn.net/zanmolcnm/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Bangala Cinema
https://y5w8j4a9.ssl.hwcdn.net/zbanglacnm/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Bollywood
https://y5w8j4a9.ssl.hwcdn.net/classic/tracks-v1a1/index.m3u8
#EXTINF:-1,ZEE CINEMA HD
https://y5w8j4a9.ssl.hwcdn.net/zcinemahd/tracks-v1a1/index.m3u8
#EXTINF:-1,ZEE CINEMA
https://y5w8j4a9.ssl.hwcdn.net/cinemausa/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Cinema Middle East
https://y5w8j4a9.ssl.hwcdn.net/zeecinemame/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Cinema UK
https://y5w8j4a9.ssl.hwcdn.net/cinemauk/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee News Bihar Jharkhand
https://y5w8j4a9.ssl.hwcdn.net/biharjharkh/tracks-v2a1/mono.m3u8
#EXTINF:-1,Zee News MPCG
https://y5w8j4a9.ssl.hwcdn.net/newsmpcg/tracks-v2a1/mono.m3u8
#EXTINF:-1,Zee Magic
https://y5w8j4a9.ssl.hwcdn.net/magic/tracks-v2a1/playlist.m3u8
#EXTINF:-1,Zee Marathi
https://y5w8j4a9.ssl.hwcdn.net/marathiusa/tracks-v2a1/mono.m3u8
#EXTINF:-1,Zee Punjabi
https://y5w8j4a9.ssl.hwcdn.net/punjabi/tracks-v1a1/index.m3u8
#EXTINF:-1,Zee Rajasthan
https://y5w8j4a9.ssl.hwcdn.net/zinguk/tracks-v1a1/index.m3u8
#EXTINF:-1,ZEE SMILE
https://y5w8j4a9.ssl.hwcdn.net/smileusa/tracks-v1a1/playlist.m3u8
#EXTINF:-1,Zee TALKIES
https://y5w8j4a9.ssl.hwcdn.net/ztalkieshd//tracks-v1a1/playlist.m3u8
#EXTINF:-1,Zee TV (Middle East)
https://y5w8j4a9.ssl.hwcdn.net/ztvme/tracks-v1a1/playlist.m3u8
#EXTINF:-1,Zee TV (Apac)
https://y5w8j4a9.ssl.hwcdn.net/apacsea/index.m3u8
#EXTINF:-1,Zee TV Canada (SUB ENG)
https://y5w8j4a9.ssl.hwcdn.net/canadahd/index.m3u8
#EXTINF:-1,Zee TV Russia
https://y5w8j4a9.ssl.hwcdn.net/russia/index.m3u8
#EXTINF:-1,Zee Zest
https://y5w8j4a9.ssl.hwcdn.net/zzesthd/tracks-v2a1/mono.m3u8
#EXTINF:-1,Zee World
https://y5w8j4a9.ssl.hwcdn.net/world/tracks-v1a1/playlist.m3u8
#EXTINF:-1,ZING
https://y5w8j4a9.ssl.hwcdn.net/zing/tracks-v1a1/playlist.m3u8

**Comment by thedudster** [comment]
@LaneSh4d0w Can you please add Star Sports HD and Non HD channels.

**Comment by thedudster** [comment]
Can someone add Star Sports channels?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Can someone add Star Sports channels?

I got Star channels but no Star Sports yet

**Comment by thedudster** [comment]
> > Can someone add Star Sports channels?
> 
> I got Star channels but no Star Sports yet

Ok, can you add all star channels to the list?

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > Can someone add Star Sports channels?
> > 
> > 
> > I got Star channels but no Star Sports yet
> 
> Ok, can you add all star channels to the list?

Sure, i'll check that out.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/122689499-33d1ae00-d223-11eb-85fa-fbf3239d5ad2.png)

Sadly they aren't working fine.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/122689538-94f98180-d223-11eb-8779-84ca38fe6b4a.png)

I also happen to have &TV but well... same thing. Stutters frame-by-frame on my side.

**Comment by thedudster** [comment]
@LaneSh4d0w is star sport working? I am not able to understand what's the error here... Are they asking for money?

**Comment by LaneSh4d0w** [comment]
@thedudster It's working, however the bandwidth linked to the server hosting this channel is very poor...

The PR i'm curating right now should answer the majority of what users wanted.

**Comment by LaneSh4d0w** [comment]
#3525 should answer some requests with Colors, Star, Zee and Sony channels.

On what I have, I also have Sun and LOTS of others to add and test. Will do it step by step.

**Comment by Nzzyme** [comment]
@LaneSh4d0w Can you please add TimesNow HD

**Comment by rupesh25358a** [comment]
hungama tv kids http://212.224.98.196:2200/R-EX/KIDS_Hungama_TV-in/index.m3u8?token=

**Comment by rupesh25358a** [comment]
> 
> 
> @LaneSh4d0w Can you please add TimesNow HD

https://timesnow-lh.akamaihd.net/i/TNHD_1@129288/master.m3u8

**Comment by Nzzyme** [comment]
> > @LaneSh4d0w Can you please add TimesNow HD
> 
> https://timesnow-lh.akamaihd.net/i/TNHD_1@129288/master.m3u8

Thanks. Can you add HD too?

**Comment by LaneSh4d0w** [comment]
HD is also on this stream. Either you wait some time until it bumps up to HD quality, either your bandwidth is not enough to support the HD quality (at least, from the server's position)

**Comment by LaneSh4d0w** [comment]
@themak1985 Not quite sure about the "One" channel. It redirects to a TV channel only available in Indonesia and its closest countries.

From what I see, there's definitely an error.
![image](https://user-images.githubusercontent.com/30985701/128151495-390b6efd-89ac-49d2-9642-1552db3daf63.png)

**Comment by Nzzyme** [comment]
> HD is also on this stream. Either you wait some time until it bumps up to HD quality, either your bandwidth is not enough to support the HD quality (at least, from the server's position)

Thanks, but that is the regular lower quality stream and not the HD channel. The HD channel is actually another channel by the name "Times Now World" (https://www.lyngsat.com/tvchannels/in/Times-Now-World.html)
Can you please add this one?

**Comment by rupesh25358a** [comment]
> 
> 
> @themak1985 Not quite sure about the "One" channel. It redirects to a TV channel only available in Indonesia and its closest countries.
> 
> From what I see, there's definitely an error.
> ![image](https://user-images.githubusercontent.com/30985701/128151495-390b6efd-89ac-49d2-9642-1552db3daf63.png)
http://50.7.161.82:8278/streams/d/SetOne/playlist.m3u8 this link works fine with me 
![Uploading Screenshot (40).png…]()

**Comment by Niyasmkkv** [comment]
Can someone add this channel pls? UBL HD. It's a Malayalam channel form UAE.

http://www.ubltv.com/live-tv/

**Comment by LaneSh4d0w** [comment]
> 
> 
> Can someone add this channel pls? UBL HD. It's a Malayalam channel form UAE.
> 
> http://www.ubltv.com/live-tv/

http://cloud.logicwebs.in:1935/ubl/ublchannel/playlist.m3u8

**Comment by ALNOID** [comment]
Zee Bangla HD pls

**Comment by Aroraggmailcom** [comment]
Star sports
