### ISSUE TITLE
Canadian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1941]
List of requests for Canadian channels from other issues:

- [ ] ABC Spark (#745)
- [ ] Addik TV (#796)
- [ ] BBC Canada (#745)
- [ ] Boomerang (#738)
- [ ] Canal D (#796)
- [ ] Cartoon Network (#737)
- [ ] Citytv (#1716)
- [ ] CMT Canada (#745)
- [ ] Cottage Life (#1716)
- [ ] CP 24 (#1716)
- [ ] Crime + Investigation (#745)
- [ ] CTV (#1587)
- [ ] CTV 2 (#1587)
- [ ] CTV News (#368)
- [ ] CTV News Ottawa (#368)
- [ ] CTV News Toronto (#368)
- [ ] CTV News Vancouver (#368)
- [ ] DejaView (#745)
- [ ] Disney Channel Canada (#745)
- [ ] Disney Junior Canada (#745)
- [ ] Disney La Chaîne (#745)
- [ ] Disney XD Canada (#745)
- [ ] Dtour (#745)
- [ ] Historia (#745)
- [ ] History Canada (#745)
- [ ] History 2 Canada (#745)
- [ ] Lifetime Canada (#745)
- [ ] MovieTime (#745)
- [ ] Nat Geo Wild Canada (#745)
- [ ] National Geographic Canada (#745)
- [ ] Nickelodeon (#742)
- [ ] RDS (#796)
- [ ] RDS 2 (#796)
- [ ] Séries Plus (#745)
- [ ] Showcase (#745)
- [ ] Slice (#745)
- [ ] Super Écran (#796)
- [ ] Teletoon (#745)
- [ ] Télétoon (#745)
- [ ] Treehouse TV (#743)
- [ ] TSN (#1827)
- [ ] TVA (#796)
- [ ] TVA Sports (#796)
- [ ] TVA Sports 2 (#796)
- [ ] V (#796)
- [ ] W Network (#745)
- [ ] YTV (#745)

**Comment by LaneSh4d0w** [comment]
RDS (Not 24/7) : https://capi.9c9media.com/destinations/rds_web/platforms/desktop/bond/contents/137513/contentpackages/78625/manifest.m3u8

**Comment by CHJ85** [comment]
Here are some canadian channels for you guys (geolocked to America). I'm not gonna add a pull request for them, because I'm lazy. 😀
BTW. FYI, just like in Europe, the Canadian Disney channels are closing down pretty soon, starting with Disney XD.

CTV Toronto:
https://cdn006.teleuptv.net/zxsJFt6VvY/playlist.m3u8
TVO:
https://cdn006.teleuptv.net/OMZsmYVUMp/playlist.m3u8
CityTV Toronto:
https://cdn006.teleuptv.net/iSykLSKMFr/playlist.m3u8
Ovation TV:
https://bozztv.com/teleyupp/teleup-ovation/playlist.m3u8
CBC Toronto:
https://cdn006.teleuptv.net/ydcl2V1MVC/playlist.m3u8

**Comment by freearhey** [comment]
@CHJ85 Thanks for your help! I've already added all the links to the playlist.

**Comment by Just4dashow** [comment]
Wassup guys !!!
Im from Montreal,Québec  

Thanks for for  your Nice job Man .... We appreciated,,im not complaint but i could Tell you, its missing Chanel  for Québec ... 
Exemple :
Super écran :1-2-3-4
Télétoon:french
Musique plus .... 

Do you   need a lists of all the Channel from Québec!?!

**Comment by LaneSh4d0w** [comment]
> Wassup guys !!!
> Im from Montreal,Québec
> 
> Thanks for for your Nice job Man .... We appreciated,,im not complaint but i could Tell you, its missing Chanel for Québec ...
> Exemple :
> Super écran :1-2-3-4
> Télétoon:french
> Musique plus ....
> 
> Do you need a lists of all the Channel from Québec!?!

It would be appreciated. We had some echoes about Super Écran, but if we can target the specific channels you need, it's even better

**Comment by Just4dashow** [comment]
Cool  i holla back you with that soon

**Comment by Just4dashow** [comment]
[Vidéotron.pdf](https://github.com/iptv-org/iptv/files/5845374/Videotron.pdf)

**Comment by Just4dashow** [comment]
By the way Do you have a link for  Movies and  séries on french version?!?

**Comment by LaneSh4d0w** [comment]
French (QC channels) 

- [ ] A&E HD
- [ ] ABC Plattsburgh
- [ ] AddikTV
- [ ] APTN
- [ ] BBC Earth
- [ ] Canal D
- [ ] Canal Vie
- [ ] CASA
- [ ] CBC Burlington
- [ ] Cinépop
- [ ] FOX HD Burlington
- [ ] FX
- [ ] Global Montréal
- [ ] Golf
- [ ] HGTV
- [ ] ICI ARTV
- [ ] ICI Explora
- [ ] ICI Radio Canada Télé HD
- [ ] ICI RDI
- [ ] Noovo
- [ ] OWN (Oprah Winfrey Network)
- [ ] Paramount Network
- [ ] PBS Pittsburgh
- [ ] Prise 2
- [ ] QUB Radio
- [ ] RDS INFO
- [ ] RDS
- [ ] RDS2
- [ ] Savoir média
- [ ] Séries+
- [ ] Showcase
- [ ] Télé-Mag
- [ ] Télé-Québec
- [ ] Télémagino
- [ ] Télétoon (French)
- [ ] TFO
- [ ] TLC
- [ ] TSN 1
- [ ] TSN 2
- [ ] TSN 3
- [ ] TSN 4
- [ ] TSN 5
- [ ]

**Comment by Just4dashow** [comment]
Still missing 

Super écran 1-2-3-4  ,:)

**Comment by Just4dashow** [comment]
Wassup Man ,im not to good with Git ....

Can you just paste me here the link of your M3U Québec playlist please
?!?if you got Time its gonna be reaaly Smart

Thanks ,merci

Bonne soireee

Le mer. 20 janv. 2021 4:31 p.m., LaneSh4d0w <notifications@github.com> a
écrit :

**Comment by FFSMNRK** [comment]
The link for CBC Ontario isn't working :( If anyone has the CBC channels, that'd be great.

**Comment by CHJ85** [comment]
@FFSMNRK All the channels have been moved to the new server. Just replace https://ts002.teleuptv.net/ with https://bozztv.com/teleyupp1/teleup- .
That goes for all the channels.

**Comment by Sphinxroot** [comment]
@freearhey   can you please test this as it should be geoblocked 

#EXTINF:-1 tvg-logo="https://github.com/Sphinxroot/Iptv-free-direct/blob/master/Images/Logo%20Station%20QC/ICI-Tele.png?raw=true" group-title="Quebec TV",ICI Tele Est-Quebec
https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_2500.m3u8

#EXTINF:-1 tvg-logo="https://github.com/Sphinxroot/Iptv-free-direct/blob/master/Images/Logo%20Station%20QC/ICI-Tele.png?raw=true" group-title="Quebec TV",ICI Tele Est-Quebec
https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_2500.m3u8|X-Forwarded-For=24.37.42.20

and see if link 2 work   thanks :)

**Comment by Just4dashow** [comment]
It works! Man i try IT with iptv tester app ...

Le lun. 1 mars 2021 12:55 a.m., Sphinxroot <notifications@github.com> a
écrit :

**Comment by freearhey** [comment]
@Sphinxroot Both links don't work for me. Tested via VLC and streamtest.in

**Comment by Just4dashow** [comment]
Same here finally

**Comment by Just4dashow** [comment]
Te limkFrom QubecWorking?

Le lun. 1 mars 2021, à 11 h 09, Yan Gosselin <losemyminds@gmail.com> a
écrit :

> Same here finally
>
> Le lun. 1 mars 2021, à 10 h 59, Aleksandr Statciuk <

**Comment by Sphinxroot** [comment]
streamtest wont handle x-forwarded  and did`nt test in other app  only on kodi  :-/

**Comment by LaneSh4d0w** [comment]
> 
> 
> @freearhey can you please test this as it should be geoblocked
> 
> #EXTINF:-1 tvg-logo="https://github.com/Sphinxroot/Iptv-free-direct/blob/master/Images/Logo%20Station%20QC/ICI-Tele.png?raw=true" group-title="Quebec TV",ICI Tele Est-Quebec
> https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_2500.m3u8
> 
> #EXTINF:-1 tvg-logo="https://github.com/Sphinxroot/Iptv-free-direct/blob/master/Images/Logo%20Station%20QC/ICI-Tele.png?raw=true" group-title="Quebec TV",ICI Tele Est-Quebec
> [https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_2500.m3u8|X-Forwarded-For=24.37.42.20](https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_2500.m3u8%7CX-Forwarded-For=24.37.42.20)
> 
> and see if link 2 work thanks :)

I think you should try like what @link8k does. He adds a parameter on the EXTINF directly. Maybe that'll work.

**Comment by KingMorisco** [comment]
> @FFSMNRK All the channels have been moved to the new server. Just replace https://ts002.teleuptv.net/ with https://bozztv.com/teleyupp1/teleup- .
> That goes for all the channels.

but do you have all playlist ?

**Comment by Extarys** [comment]
Not sure how I would add this, but I got TVA working with a single m3u8 file:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio1",NAME="FRA",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="FRA",URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/05.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio1",NAME="FRM",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="FRM",URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/06.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1665250,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=29.970,AUDIO="audio1"
https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104078,CODECS="avc1.4D4028",RESOLUTION=960x540,URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02-iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=249820,CODECS="mp4a.40.2",AUDIO="audio1"
https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/05.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1103293,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=29.970,AUDIO="audio1"
https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/01.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=68955,CODECS="avc1.4D4028",RESOLUTION=480x270,URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/01-iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2451989,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="audio1"
https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/03.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=153249,CODECS="avc1.4D4028",RESOLUTION=1280x720,URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/03-iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4250250,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970,AUDIO="audio1"
https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/04.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=265640,CODECS="avc1.640029",RESOLUTION=1920x1080,URI="https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/04-iframe.m3u8"
```

- No idea how long this will work
- Or how to properly add it to `ca.m3u`

**Logo**: https://upload.wikimedia.org/wikipedia/fr/2/23/TVA_%28logo%2C_2020%29.svg
**Language**: French
**Country/Region:** Canada, Province of Quebec
**Type:** General public channel/news channel (Similar to ICI Télé)

**Comment by brainfork** [comment]
I've got a bunch of Global and CBC channels (along with some others) added in this list: https://github.com/brainfork/iptv/blob/master/iptv.m3u

Most of them work, I'm still compiling other channels that I can find as well

**Comment by FinallyCanuck** [comment]
Looking for CityTV Toronto. Was previously available at https://bozztv.com/teleyupp1/teleup-iSykLSKMFr/playlist.m3u8 but that URL now returns a 404 error.

**Comment by LaneSh4d0w** [comment]
I had made a test with CityTV Toronto actually : https://iptv-all.lanesh4d0w.codes/canada/citytv-toronto
