### ISSUE TITLE
UK Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1943]
List of requests for UK channels from other issues:

- [ ] 4seven (#871)
- [ ] BBC 1 (#871)
- [ ] BBC 2 (#871)
- [ ] BBC 4 (#871)
- [ ] BBC Earth (#1379)
- [ ] BBC Red Button (#1656)
- [ ] BT Sport (#1380)
- [ ] Cartoon Network UK (#1714)
- [ ] Channel 4 (#871)
- [ ] Crime + Investigation UK (#1379)
- [ ] Disney Channel UK (#1714)
- [ ] itv 1 (#871)
- [ ] itv 2 (#871)
- [ ] itv 3 (#871)
- [ ] itv 4 (#871)
- [ ] Nat Geo Wild UK (#1714)
- [ ] National Geographic UK (#871, #1714)
- [ ] Nickelodeon UK (#1714)
- [ ] Sky (#871)
- [ ] Sky Sports (#1380)

**Comment by CHJ85** [comment]
Some UK channels for you:
BBC One / Cbeebies: http://51.52.156.22:8888/http/003
BBC One Scotland: http://51.52.156.22:8888/http/001
BBC World News: http://51.52.156.22:8888/http/004
BBC Alba: http://51.52.156.21:8888/http/001
ITV 2: http://51.52.156.22:8888/http/005
ITV 3: http://51.52.156.22:8888/http/006
ITV 4: http://51.52.156.22:8888/http/007
Channel 4: http://51.52.156.21:8888/http/003
Film 4: http://51.52.156.22:8888/http/008
PBS: http://51.52.156.22:8888/http/012

**Comment by CHJ85** [comment]
Oh and btw.
BBC Earth is not a UK channel.
It's BBC's international nature documentaries channel.
And Disney Channel UK was closed down months ago.

**Comment by freearhey** [comment]
@CHJ85 Thanks for the links and additional information! I added a note about Disney being closed to the list. As for BBC Earth, we don't sort the channels by the country in which they are broadcast, but by where they are produced.

**Comment by CHJ85** [comment]
Well. I mean, BBC Earth is available in Asia, Croatia, Cyprus, the Scandinavian countries, Greece, Hungary, Latin America, Montenegro & Bosnia, Romania, Serbia, South Africa Slovenia and Turkey.
There's no UK version of the channel. Thus different time zones.
But whatever.

**Comment by LaneSh4d0w** [comment]
ITV 1 : https://edge-1180-ch-gv.filmon.com/live/1817.low.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbea51cbc96ddfe5b9ed3f8fe3286df6a738d387fb5d973922aee718f6f262d72e77aa3f2800c82f00d54c2dc8f926111cb056be63994f8ff6743917e31ecaee1abc63716f341f1b8af34a8eb5f4e87753cdcea6ace8918d1d01e2e1b940f686332b342e4550d5fd06fb98f2a4e7faffad785350af010380843d7f2453dfe5d060b0d48a37c108ae53fb6c

**Comment by semofx** [comment]
T

**Comment by CHJ85** [comment]
@LaneSh4d0w Least you can do is extract the encrypted URL so that the channel actually works. Here you go @freearhey. Here's ITV1!
http://sportportal1.akamaized.net/hls/live/702646/itvlive/ITV1PORTAL2/master.m3u8

**Comment by LaneSh4d0w** [comment]
@CHJ85 Had no view for this one. Glad you found out !

**Comment by freearhey** [comment]
@CHJ85 Unfortunately, the streamer still does not work:
<img width="755" alt="Captura de pantalla 2021-01-16 a las 17 03 01" src="https://user-images.githubusercontent.com/7253922/104813846-c9a08180-581c-11eb-85c6-b78cb1bc1167.png">
Tested in VLC player and streamtest.in

**Comment by CHJ85** [comment]
@freearhey Might be Geo-locked where you're located.
Tried with my American IP and various European VPN locations. Works just fine.

**Comment by LaneSh4d0w** [comment]
> @freearhey Might be Geo-locked where you're located.
> Tried with my American IP and various European VPN locations. Works just fine.

Doesn't work from me, French IP

**Comment by CHJ85** [comment]
@LaneSh4d0w I just connected to France, Strasbourg. Works just fine.
Oh well.

**Comment by LaneSh4d0w** [comment]
Just retried, works for me now. Might have an outage at that time

![Screenshot_20210116_152421_org.videolan.vlc.jpg](https://user-images.githubusercontent.com/30985701/104814418-0796a900-580f-11eb-95c7-21a9a28d2b84.jpg)

**Comment by trancer1994** [comment]
BBC 2
https://vs-dash-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_two_hd/bbc_two_hd.isml/pc_hd_abr_v2_dash.mpd

BBC 4
https://vs-dash-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_four_hd/bbc_four_hd.isml/pc_hd_abr_v2_dash.mpd

The URL for BBC 1 is actually https://vs-dash-uk.live.cf.md.bbci.co.uk/pool_902/live/uk/bbc_one_hd/bbc_one_hd.isml/pc_hd_abr_v2_dash.mpd

Again, as someone else said above, BBC Earth is not a UK channel.

**Comment by CHJ85** [comment]
@trancer1994 These are encrypted DASH streams.

**Comment by LaneSh4d0w** [comment]
> BBC 2
> https://vs-dash-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_two_hd/bbc_two_hd.isml/pc_hd_abr_v2_dash.mpd
> 
> BBC 4
> https://vs-dash-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_four_hd/bbc_four_hd.isml/pc_hd_abr_v2_dash.mpd
> 
> The URL for BBC 1 is actually https://vs-dash-uk.live.cf.md.bbci.co.uk/pool_902/live/uk/bbc_one_hd/bbc_one_hd.isml/pc_hd_abr_v2_dash.mpd
> 
> Again, as someone else said above, BBC Earth is not a UK channel.

Tried once with my mobile browser, 403 on both.

**Comment by trancer1994** [comment]
LaneSh4d0w commented 2 hours ago  You can use a UK vpn. Unfortunately there's no way I know to convert them to globally-accessible streams. @CHJ85 I know. If you can't use those, here's an alternate hls stream: http://vs-hls-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_two_hd/bbc_two_hd.isml/pc_hd_abr_v2_hls.m3u8 (this is the non-secure hls stream of BBC Two, but still unfortunately geolocked to the UK). BBC Four's non-secure hls stream is http://vs-hls-uk-live.bbcfmt.s.llnwi.net/pool_902/live/uk/bbc_four_hd/bbc_four_hd.isml/pc_hd_abr_v2_hls.m3u8 and BBC One's stream is http://vs-hls-uk.live.cf.md.bbci.co.uk/pool_902/live/uk/bbc_one_hd/bbc_one_hd.isml/pc_hd_abr_v2_hls.m3u8

**Comment by kbhasi** [comment]
>BBC Red Button

As far as I know, that's not a channel, but the BBC's implementation of HbbTV.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/119471237-633aeb00-bd49-11eb-881b-2bd9c68012d1.png)

Streamlink recognizes the Filmon links, and goes past the 30-second blocking mark.
