### ISSUE TITLE
Iraqi Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1955]
List of requests for Iraqi channels from other issues:

- [ ] Ava Media TV (#1498)
- [ ] Iraqia Kurdish (#1498)
- [ ] [Iraqia Sport](https://www.lyngsat.com/tvchannels/iq/Iraqia-Sport.html) (Al Iraqiya Sports) (#722)
- [ ] Korek TV (#1498)
- [ ] NRT 4 (#1498)
- [ ] NRT TV HD (#1498)
- [ ] WAAR TV HD (#1498)

**Comment by freearhey** [comment]
@Sphinxroot If you have links to channels from this list, it is better to add them directly to the playlist via pull request.

**Comment by Mennaruuk** [comment]
Ava TV's box should be checked, channel was added already.

**Comment by freearhey** [comment]
@Mennaruuk I don't see it on the playlist. Could you post a link to it here?

**Comment by Mennaruuk** [comment]
It's called Ava Entertainment. [iq.m3u](https://github.com/iptv-org/iptv/blob/master/channels/iq.m3u)

**Comment by freearhey** [comment]
@Mennaruuk So [this](https://www.lyngsat.com/tvchannels/iq/Ava-Entertainment.html) and [this](https://www.lyngsat.com/tvchannels/iq/Ava-TV.html) are the same channel?

**Comment by Mennaruuk** [comment]
So I researched this, and they have the same name despite being different channels. Yes, quite confusing. One is called Ava TV, made by [Ava Entertainment](https://www.avaentertainment.net/en/live). The other is also called Ava TV, but it's more commonly known as [ATV Kurd](https://www.instagram.com/atv__kurd), or Ava Media TV as described in #1498. As such, the box should be kept unchecked till a stream for Ava Media TV/ATV Kurd is found.
