### ISSUE TITLE
Qatari Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1956]
List of requests for Qatari channels from other issues:

- [ ] Baraem (#1046)
- [x] BeIn Sports 1 (#722, #2231, #2409, #2410, #2433, #2716) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 2 (#722, #2231, #2433) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 3 (#722, #2231) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 4 (#722, #2231) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 5 (#722, #2231) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 6 (#722) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 7 (#722) (added via https://github.com/iptv-org/iptv/pull/3649)
- [x] BeIn Sports 8 (#722) (added via https://github.com/iptv-org/iptv/pull/3649 (beIN Premium 1))
- [x] BeIn Sports 9 (#722) (added via https://github.com/iptv-org/iptv/pull/3649 (beIN Premium 2))
- [ ] BeIn Sports 10 (#722, #1970)
- [ ] BeIn Sports Max Malaysia (#1599)
- [ ] BeIn Sports USA (#1380)
- [ ] Jeem TV (#1046)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by LaneSh4d0w** [comment]
BeIN Sports Xtra (English) : https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5df975e2b27cf5000921c102/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=740&deviceId=5df975e2b27cf5000921c102&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false

Those things are needed, comes from some Pluto TV app data.

**Comment by exyanis** [comment]
QATAR TV
https://qatartv.akamaized.net/hls/live/2026573/qtv1/master720p.m3u8

**Comment by freearhey** [comment]
@exyanis Added.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/126818518-22554f60-1d1e-4c6f-81aa-80cff8d82bdf.png)

BeIN Sports 8 and 9 are beIN Premium 1 and 2.
