### ISSUE TITLE
Romanian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1957]
List of requests for Romanian channels from other issues:

- [x] Antena 1 (#762, #1244)
- [x] Antena Stars (#1244)
- [x] B1 (#1244) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] Digi 24 (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] Digi Animal World (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [x] Digi Life Romania (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [ ] Digi Sport 1 Romania (#762)
- [ ] Digi Sport 2 Romania (#762)
- [ ] Digi Sport 3 Romania (#762)
- [ ] Digi Sport 4 Romania (#762)
- [ ] Digi World Hungary (#718)
- [x] Digi World Romania (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [ ] Favorit TV (#762)
- [ ] Film Now (#762)
- [x] Happy Channel (#762)
- [x] H!t Music Channel Romania (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [x] Kiss TV (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] LookPlus (#762) ([replaced by LookSport+](https://en.wikipedia.org/wiki/LookPlus)) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] LookSport (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] LookSport 2 (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] LookSport 3 (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] ~~Megamax (#762)~~ (channel was [closed](https://en.wikipedia.org/wiki/Megamax))
- [x] Music Channel Romania (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] Naşul TV (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [ ] Național 24 Plus (#762)
- [ ] National TV (#762)
- [ ] Neptun TV (#762)
- [x] Prima TV (#762, #1244) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [ ] Pro 2 (#762, #1244)
- [ ] Pro Cinema (#762)
- [ ] Pro Gold (#762)
- [ ] Pro X (#762)
- [x] Realitatea TV (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [ ] România TV (#762)
- [ ] Taraf TV (#762)
- [ ] Telekom Sport 1 (#762)
- [ ] Telekom Sport 2 (#762)
- [ ] Telekom Sport 3 (#762)
- [ ] Telekom Sport 4 (#762)
- [x] Travel Mix (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] TV Paprika Romania (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [x] TVR 1 (#762)
- [x] TVR 2 (#762)
- [x] TVR 3 (#762)
- [x] UTV Romania (#762) (added via 4b0597457aae5617acf0e421f7631bf7768b8c5c)
- [x] Zu TV (#762)

**Comment by trancer1994** [comment]
Some of these are tokenised unfortunately I think, and am not sure how long after you use them they will expire. The Look Sport stuff does work though surprisingly. Look Sport 1/2/3 HD is really just Look Sport 1/2/3.

Here's what I was able to find for you: 

Antena 1
https://ivm.antenaplay.ro/live/a1/playlist.m3u8?starttime=1611066858&endtime=1611074088&source=web&token=Wm6u7j57WarW0UJQxMvggG8Lua4=
Antena Stars
https://ivm.antenaplay.ro/live/astars/playlist.m3u8?starttime=1611067319&endtime=1611074549&source=web&token=72WPx0wKb1AmEr2VNzq5o0xqE4k=
B1
https://stream.adunity.com/b1/b1.m3u8
Digi 24
http://d-e-02.cdn.rdsnet.ro/DVR/digi24hdb.stream/playlit.m3u8
or
https://edge74.rcs-rds.ro/V4-5289983-a2e60f05d11c9ffd7da25758ed3c9f0d-88425061-0-1611067955-477-digi24/digi24/digi24-abr.m3u8?is=4&ns=digi24&pe=site&s=site&sn=digi24.ro&p=browser&pd=windows&quality=hq&t=00000000000000000000000000000000&t4=V4-5289983-a2e60f05d11c9ffd7da25758ed3c9f0d-88425061-0-1611067955-477-digi24
or
https://edge74.rcs-rds.ro/V4-5289983-a2e60f05d11c9ffd7da25758ed3c9f0d-88425061-0-1611067955-477-digi24/digi24/digi24-abr.m3u8
Happy Channel
https://ivm.antenaplay.ro/live/happy/playlist.m3u8?starttime=1611068361&endtime=1611075591&source=web&token=MQE0TzUbsNNmmq9R7BJrfDyAac0=
Kanal D
https://stream1.kanald.ro/iphone/live.m3u8
Kiss TV
https://fms-https1.mediadirect.ro/live3/_definst_/kiss.smil/playlist.m3u8?publisher=83
Music Channel Romania
https://edge126.rcs-rds.ro/utvedge/musicchannelhq.stream/index.m3u8
or
https://edge126.rcs-rds.ro/digi24edge/smil:musicchannel.smil/index.m3u8
Second stream doesn't work; use first link

#EXTINF:0,Look Sport
https://stream1.1616.ro:1945/look/livestream/playlist.m3u8?wowzatokenendtime=1608539469&wowzatokenhash=NqSD4qaHc94SbTW05NBB-lXC78ZiAOIbnbUBOHj1DAM=&wowzatokenstarttime=1608496269
#EXTINF:0,Look Sport + HD
https://stream1.1616.ro:1945/lookplus/livestream/playlist.m3u8?wowzatokenendtime=1608539469&wowzatokenhash=NqSD4qaHc94SbTW05NBB-lXC78ZiAOIbnbUBOHj1DAM=&wowzatokenstarttime=1608496269
#EXTINF:0,Look Sport 2 HD
https://stream1.1616.ro:1945/looksport2/livestream/playlist.m3u8?wowzatokenendtime=1608539469&wowzatokenhash=NqSD4qaHc94SbTW05NBB-lXC78ZiAOIbnbUBOHj1DAM=&wowzatokenstarttime=1608496269
#EXTINF:0,Look Sport 3 HD
https://stream1.1616.ro:1945/looksport3/livestream/playlist.m3u8?wowzatokenendtime=1608539469&wowzatokenhash=NqSD4qaHc94SbTW05NBB-lXC78ZiAOIbnbUBOHj1DAM=&wowzatokenstarttime=1608496269
Naşul TV
https://5ab29cc78f681.streamlock.net/NasulTV/livestream/playlist.m3u8
Prima TV
https://stream1.1616.ro:1945/prima/livestream/playlist.m3u8?wowzatokenendtime=1611115175&wowzatokenhash=hOdIznDoakApEuQ8FaFI3yrJuBMZHqCB7B3cWTmRWsc=&wowzatokenstarttime=1611071975
Pro 2
https://cmero-ott-live-sec.ssl.cdn.cra.cz/xzqEYFgi6etF1VVCIpgCtA==,1611081220/channels/cme-ro-pro2/playlist.m3u8
Pro Cinema
Pro Cinema
https://cmero-ott-live-sec.ssl.cdn.cra.cz/UixHJ8--YYPy9R-CUz2S3A==,1611081839/channels/cme-ro-procinema/playlist.m3u8
Pro Gold
https://cmero-ott-live-sec.ssl.cdn.cra.cz/FgXSS2vdbphW75-fKsM8aA==,1611082092/channels/cme-ro-progold/playlist.m3u8
Realitatea TV seems to be
https://live.realitatea.net/livertmp/plus/playlist.m3u8
Romania TV
https://livestream.romaniatv.net/clients/romaniatv/playlist.m3u8
Travel mix
http://89.38.8.131:39520
TVR 1
https://mn-nl.mncdn.com/tvr1_live/smil:tvr1_live.smil/index.m3u8
TVR 2
https://mn-nl.mncdn.com/tvr2_test/smil:tvr2_test.smil/index.m3u8
TVR 3
https://mn-nl.mncdn.com/tvr3_test/smil:tvr3_test.smil/index.m3u8
UTV
https://edge126.rcs-rds.ro/utvedge/utvhq.stream/index.m3u8
Zu TV
https://ivm.antenaplay.ro/live/zutv/playlist.m3u8?starttime=1611075760&endtime=1611082990&source=web&token=9qqd7vCC07UQ7fE4y8UJT-qDKQs=

You're welcome.

**Comment by freearhey** [comment]
@trancer1994 Great job!

I've added most of the channels to the playlist, except for links from `https://cmero-ott-live-sec.ssl.cdn.cra.cz` and `https://ivm.antenaplay.ro`, which don't work for me. 

Also I moved the `Kanal D` to the Turkish playlist, as I understand it is the [regular version](https://www.lyngsat.com/tvchannels/tr/Kanal-D.html) of the channel and not the [Romanian one](https://www.lyngsat.com/tvchannels/tr/Kanal-D-Romania.html). Correct me if I'm wrong.

**Comment by Liniuta** [comment]
Hi! I have here some channels to add to this file if you want. 90% of them should working.
**#EXTINF:0 ,AXN SPIN
http://edge76.rcs-rds.ro/digiedge2/axnspinehq.stream/index.m3u8?is=57&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,AXN
http://edge76.rcs-rds.ro/digiedge2/axnehd.stream/index.m3u8?is=44&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,AXN BLACK
http://edge76.rcs-rds.ro/digiedge2/axnblackehq.stream/index.m3u8?is=45&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,TV 1000
http://edge76.rcs-rds.ro/digiedge2/tv1000ehq.stream/index.m3u8?is=43&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,EUROSPORT 1
http://edge76.rcs-rds.ro/digiedge2/eurosportehq.stream/index.m3u8?is=31&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,EUROSPORT 2
http://edge76.rcs-rds.ro/digiedge2/eurosport2ehq.stream/index.m3u8?is=32&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,VIASAT NATURE HD
http://edge76.rcs-rds.ro/digiedge2/viasatnatureehq.stream/index.m3u8?is=42&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,VIASAT HISTORY
http://82.76.40.76/digiedge2/viasathistoryehq.stream/index.m3u8?is=41&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,VIASAT EXPLORER
http://edge76.rcs-rds.ro/digiedge2/viasatexplorerehq.stream/index.m3u8?is=40&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,NATIONAL GEOGRAPHIC HD
http://edge76.rcs-rds.ro/digiedge2/nationalgeographicehd.stream/index.m3u8?is=19&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,NAT GEO WILD
http://edge76.rcs-rds.ro/digiedge2/nationalgeographicwildehd.stream/index.m3u8?is=33&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,HISTORY HD
http://edge76.rcs-rds.ro/digiedge2/historychannelehd.stream/index.m3u8?is=20&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,DISCOVERY CHANNEL
http://82.76.40.76/digiedge2/discoveryehq.stream/index.m3u8?is=71&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,DIGI WORLD
http://edge76.rcs-rds.ro/digiedge2/digiworldehd.stream/index.m3u8?is=5&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,DIGI ANIMAL WORLD
http://edge76.rcs-rds.ro/digiedge2/digianimalworldehd.stream/index.m3u8?is=16&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,BBC EARTH
http://edge76.rcs-rds.ro/digiedge2/bbcearthehq.stream/index.m3u8?is=67&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,DAVINCI LEARNING
http://82.76.40.76/digiedge2/davincilearningehq.stream/index.m3u8?is=66&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,U TV
http://edge76.rcs-rds.ro/utvedge/utvlivehls/playlist.m3u8
#EXTINF:0 ,KISS TV
http://82.76.40.76/digiedge2/kisstvehq.stream/index.m3u8?is=34&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,H!T MUSIC CHANNEL
http://82.76.40.76/digiedge2/hitmusicchannelehq.stream/index.m3u8?is=35&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,TV PAPRIKA
http://edge76.rcs-rds.ro/digiedge2/tvpaprikaehq.stream/index.m3u8?is=39&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,TRAVEL MIX
http://82.76.40.76/digiedge2/travelmixchannelehq.stream/index.m3u8?is=74&src=digi-online.ro&t=00000000000000000000000000000000
#EXTINF:0 ,TRAVEL CHANNEL
http://edge76.rcs-rds.ro/digiedge2/travelchannelehd.stream/index.m3u8?is=21&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,TLC
http://82.76.40.76/digiedge2/tlcehq.stream/index.m3u8?is=72&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,E! ENTERTAINMENT
http://82.76.40.76/digiedge2/eentertainmentehq.stream/index.m3u8?is=76&src=app&t=00000000000000000000000000000000
#EXTINF:0 ,DIGI LIFE
http://edge76.rcs-rds.ro/digiedge2/digilifeehd.stream/index.m3u8?is=6&src=app&t=00000000000000000000000000000000**

**Comment by freearhey** [comment]
@Liniuta I added all the links to the playlist except EUROSPORT, DISCOVERY CHANNEL, TRAVEL CHANNEL and TLC. We cannot add these channels because of a claim by the copyright holder: https://github.com/iptv-org/iptv/issues/1831

**Comment by LaneSh4d0w** [comment]
Nice job ! The query parameters can be cleared, it seems to work without it as I see.

**Comment by LaneSh4d0w** [comment]
All links except U TV aren't working for me. Geolocked ?

**Comment by freearhey** [comment]
No, the links just stopped working and have already been removed from the playlist.

**Comment by trancer1994** [comment]
What links don't work?

**Comment by freearhey** [comment]
I meant the links from this comment: https://github.com/iptv-org/iptv/issues/1957#issuecomment-773533738
