### ISSUE TITLE
Algerian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1961]
List of requests for Algerian channels from other issues:

- [x] Al Anis TV (#1461) (added via #2822)
- [x] Algerie 3 (Thalitha A3) (#863) (added via #2822)
- [x] [Algerie 4](https://www.lyngsat.com/tvchannels/dz/TV-4-Amazigh.html) (TV 4 Amazigh) (#863) (added via #2822)
- [x] [Algerie 5](https://www.lyngsat.com/tvchannels/dz/TV-5-Coran.html) (TV 5 Coran) (#863) (added via #2822)
- [x] Bahia TV (#863, #1461) (added via #2822)
- [x] Canal Algérie (#863) (added via #1960)
- [x] Echorouk TV (#863) (added via #2082)
- [x] Echorouk TV News (#863, #1461) (added via #2082)
- [x] El Bilad TV (#1461) (added via #2822)
- [x] El Djazaïr N1 (#1461) (added via #2822)
- [x] El Djazairia One (#1461) (added via #2822)
- [x] El Fadjer TV (#1461) (added via #2822)
- [x] El Hayat TV (#1461) (added via #2822)
- [x] Lina TV (#1461) (added via #2822)
- [ ] Numidia TV (#1461)
- [x] Samira TV (#1461) (added via #2822)

**Comment by themak1985** [comment]
@Nintendocustom, do you manage https://iptv.repl.co/? Many of these channels are tokenized and found at https://www.htatv.com/ - is this something you would be willing to add to your program?

**Comment by Nintendocustom** [comment]
Sorry for the late reply @themak1985 , but the website is whitelisting the IP addresses, there is nothing I can do about that.

**Comment by LaneSh4d0w** [comment]
https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/

Work in progress...

**Comment by LaneSh4d0w** [comment]
For the moment, it's a listing. I'm looking to dynamically inject the links.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Sorry for the late reply @themak1985 , but the website is whitelisting the IP addresses, there is nothing I can do about that.

In my recent testings, it seems it worked. I had the m3u files that were given me.
I'm testing on my side, and i'll hook you up if I got an answer, better give this to you 'cause you've made a whole list.

**Comment by LaneSh4d0w** [comment]
Indeed, if I make a fetch using the REPLs it doesn't work. However, a token i've created using the website works. If you try using my website, every thing should work.

**Comment by Sphinxroot** [comment]
#2822

**Comment by LaneSh4d0w** [comment]
Every channel covered by #1461 is now available in the playlists.

**Comment by freearhey** [comment]
@LaneSh4d0w I don't see the Numidia TV in the playlist, or is it called something else?

**Comment by LaneSh4d0w** [comment]
I don't think there's a live stream that exists for Numidia, apart of some XTream codes stream which are unreliable. The only one that streamed it was HTA, but they cut off the stream recently.

https://cdn02.hta.dz/abr_htatv/NUMIDIA_TV/htatv/NUMIDIA_TV_HD_720p/chunks.m3u8 <- I even tried remaking the links using what I had, but nope. Dead end here.

**Comment by freearhey** [comment]
@LaneSh4d0w Then it is better to leave the topic open in case a working link does appear.

**Comment by LaneSh4d0w** [comment]
Here's basically how to make them work locally. 

```
app.get("/algeria/hta_all_in_1", function(req, res) {
    fetch("https://token.kube.easybroadcast.fr/authtoken?url=http://apphta.easybroadcast.fr/apphta", {method: "GET", headers: {"Referer": "https://htatv.com/"}})
        .then(response => response.text())
        .then(result => {
            let channel = req.query.channel;
            if (!channel) {
                res.send("No channel has been given.")
            } else {
                res.redirect('https://cdn02.hta.dz/abr_htatv/' + channel + '/playlist.m3u8' + result)
            }
        })
});
```

If you add a proxy to it, and that you use the same proxy for your own connection, stream will work, otherwise good luck.

**Comment by freearhey** [comment]
Closed in favor #4296
