### ISSUE TITLE
Irish Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1966]
List of requests for Irish channels from other issues:

- [ ] RTÉ 2 (#1280)
- [ ] RTÉ Jr (#1280)
- [ ] RTÉ One (#1280)
- [ ] Virgin Media One (#1280)
- [ ] Virgin Media Three (#1280)
- [ ] Virgin Media Two (#1280)

**Comment by Sphinxroot** [comment]
https://www.rte.ie/player/

#EXTINF:-1,RTE 1 onnow
https://live.rte.ie/live/a/channel1/channel1.isml/.mpd

+ Expire timer  + IP= Yours  + token

#EXTINF:-1,RTE 2 
https://live.rte.ie/live/a/channel2/channel2.isml/.mpd

+ Expire timer  + IP= Yours  + token 

#EXTINF:-1,RTE News
https://live.rte.ie/live/a/channel3/channel3.isml/.mpd

+ Expire timer  + IP= Yours  + token 

#EXTINF:-1 tvg-id="RTENewsNow.ie" tvg-name="RTE News Now" tvg-country="IE" tvg-language="English" tvg-logo="http://static.epg.best/ie/RTENewsNow.ie.png" group-title="News",RTE News Now (1080p)
https://live.rte.ie/live/a/channel3/news.isml/news.m3u8

only audio stream
#EXTINF:-1 tvg-id="RTENewsNow.ie" tvg-logo="https://upload.wikimedia.org/wikipedia/en/d/db/Rtenewsnownewlogo.png" group-title="IRLANDA",RTE News Now
https://live.rte.ie/live/a/channel3/news.isml/.m3u8

if someone can find a way to rename RTE 1 & 2 as the news channel  it might work as a .m3u8 link

**Comment by Nintendocustom** [comment]
@Sphinxroot this is not that simple, the website uses Widevine (MPEG-CENC).

**Comment by 129612231-scripts** [comment]
#EXTM3U
#EXTINF:0 tvg-country="IE" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/e/e4/RT%C3%89_One_2014.svg/revision/latest/scale-to-width-down/1000?cb=20210310103914" group-title="Kids",RTE ONE
http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1137.ts
#EXTINF:0 tvg-country="IE" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/c/c4/RT%C3%892_2014.svg/revision/latest/scale-to-width-down/1000?cb=20210304161956" group-title="Kids",RTE2
http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1138.ts
#EXTINF:0 tvg-country="IE" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/b3/RTEjr.svg/revision/latest/scale-to-width-down/500?cb=20210310081522" group-title="Kids",RTE JNR
http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1139.ts
#EXTINF:0 tvg-country="IE" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/9/97/Virgin_Media_One_2018.svg/revision/latest/scale-to-width-down/1000?cb=20180829221837" group-title="Kids",VIRGIN MEDIA ONE
http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1143.ts
#EXTINF:0 tvg-country="IE" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/4/46/Virgin_Media_Two_2018.svg/revision/latest/scale-to-width-down/1000?cb=20180829232245" group-title="Kids",VIRGIN MEDIA TWO
http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1144.ts

there are the links, except for virgin media three, because they all seem to be virgin media one.
