### ISSUE TITLE
Malaysian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1982]
List of requests for Malaysian channels from other issues:

- [ ] Astro AEC (#1599)
- [ ] Astro AOD 351 (#1599)
- [ ] Astro AOD 352 (#1599)
- [ ] Astro AOD 353 (#1599)
- [ ] Astro AOD 354 (#1599)
- [ ] Astro AOD 355 (#1599)
- [ ] Astro Arena (#1599)
- [ ] Astro Awani (#1599)
- [ ] Astro BollyOne HD (#1599)
- [ ] Astro Ceria (#1599)
- [ ] Astro Cricket (#1599)
- [ ] Astro Hua Hee Dai (#1599)
- [ ] Astro Oasis (#1599)
- [ ] Astro Prima (#1599)
- [ ] Astro Quan Jia HD (#1599)
- [ ] Astro Ria (#1599)
- [ ] Astro Shuang Xing (#1599)
- [ ] Astro SuperSport (#1599)
- [ ] Astro SuperSport 2 (#1599)
- [ ] Astro SuperSport 3 (#1599)
- [ ] Astro SuperSport 4 (#1599)
- [ ] Astro Vinmeen HD (#1599)
- [ ] Astro Warna (#1599)
- [ ] Astro Xiao Tai Yang (#1599)
- [ ] Egg Network (#1599)
- [ ] Go Shop Malay 111 (#1599)
- [ ] Go Shop Malay 118 (#1599)
- [ ] Go Shop Malay 120 (#1599)
- [ ] Golf Channel Malaysia (#1599)
- [ ] HBO Malaysia (#1599)
- [ ] Hello (#1599)
- [ ] Kix Malaysia (#1599)
- [ ] Naura (#1599)
- [ ] RTM TV 1 (#1599)
- [ ] RTM TV 2 (#1599)
- [ ] RugbyPass TV (#1599)
- [ ] TV 3 (#1599)
- [ ] TV Alhijrah (#1599)

**Comment by teamelite2019** [comment]
8tv m3u is not working anymore, please help

**Comment by LaneSh4d0w** [comment]
> 
> 
> 8tv m3u is not working anymore, please help

It seems 8TV is now redirecting to Xtra. Added 8TV on post above, try and see if it works.

**Comment by trancer1994** [comment]
8tv, as well as tv9, ntv, tv3, and one of the other channels on that site (I forget which) all use Dailymotion I think.

**Comment by LaneSh4d0w** [comment]
> 8tv, as well as tv9, ntv, tv3, and one of the other channels on that site (I forget which) all use Dailymotion I think.

Indeed, just watch the links I posted to have an idea of what they look like.

**Comment by teamelite2019** [comment]
https://stream-08.ix7.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHUdHfidFKbmHh_0-rtrv160)/dm/3/x6qud17/s/live-3.m3u8. i tried this, it does not works, not sure if i have copied correct URL ? someone can help ?

**Comment by LaneSh4d0w** [comment]
> https://stream-08.ix7.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHUdHfidFKbmHh_0-rtrv160)/dm/3/x6qud17/s/live-3.m3u8. i tried this, it does not works, not sure if i have copied correct URL ? someone can help ?

It's not just you, 403 on testings. Might be a change in the servers or they cut and came back after (server change then)

**Comment by LaneSh4d0w** [comment]
It seems they took action and georestricted every channel... except for Drama Sangai x)

**Comment by LaneSh4d0w** [comment]
Astro Awani : https://awanitv.akamaized.net/hls/live/2017836/LiveTV1/stream05/streamPlaylist.m3u8

**Comment by LaneSh4d0w** [comment]
Some Dailymotion channels can soon be added with #2833 's findings.

**Comment by LaneSh4d0w** [comment]
Astro Supersport 4 : http://159.192.73.198:1072/astro4

**Comment by Angel6211** [comment]
Astro Wah Lai Toi  and Astro Hua Hee Dai  not working anymore, please help
