### ISSUE TITLE
Saudi Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1989]
List of requests for Saudi channels from other issues:

- [x] Al Ekhbariya (#1873) (added via https://github.com/iptv-org/iptv/commit/f69b0dbf8a734fdb13e28fbc968bd5121fdfc38d)
- [x] Al Saudiya (#1873) (added via https://github.com/iptv-org/iptv/commit/f69b0dbf8a734fdb13e28fbc968bd5121fdfc38d)
- [x] SBC (#1873) (added via https://github.com/iptv-org/iptv/commit/8081d3c94108aba774ce959914f1d16a139cdb9e)
- [x] Thikrayat TV (#1873) (قناة ذكريات) (added via https://github.com/iptv-org/iptv/commit/f69b0dbf8a734fdb13e28fbc968bd5121fdfc38d)

**Comment by trancer1994** [comment]
SBC
https://cllive.itworkscdn.net/sbclive/token=nva=1611091186~dirs=1~hash=0f4b750a797f014a3ba8b/sbc.smil/playlist.m3u8

**Comment by freearhey** [comment]
@trancer1994 Thank you! I've already added the channel to the playlist.

**Comment by LaneSh4d0w** [comment]
Token based livestream for SBC. Let me see...

**Comment by Nintendocustom** [comment]
I can help with token based streams.

**Comment by link8k** [comment]
If you self-host your playlist you can scrape the expiring url with

```
echo '#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://shashatcom.faulio.com/storage/mediagallery/f3/12/fullhd_6aacb64b11bd07aa726b64ea478a15f7690bb830.png" group-title="",SBC' >> playlist.m3u8;
curl -s https://shashatcom.faulio.com/api/v1/channels/1 | python -c 'import json, sys; print(json.loads(sys.stdin.read())["streams"]["hls"]);' >> playlist.m3u8;
```

Change https://shashatcom.faulio.com/api/v1/channels/ **1** for other shashatcom channels

**Comment by LaneSh4d0w** [comment]
> 
> 
> If you self-host your playlist you can scrape the expiring url with
> 
> ```
> echo '#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://shashatcom.faulio.com/storage/mediagallery/f3/12/fullhd_6aacb64b11bd07aa726b64ea478a15f7690bb830.png" group-title="",SBC' >> playlist.m3u8;
> curl -s https://shashatcom.faulio.com/api/v1/channels/1 | python -c 'import json, sys; print(json.loads(sys.stdin.read())["streams"]["hls"]);' >> playlist.m3u8;
> ```
> 
> Change https://shashatcom.faulio.com/api/v1/channels/ **1** for other shashatcom channels

Interesting find...

**Comment by Nintendocustom** [comment]
SBC: https://iptv--iptv.repl.co/Arabic/SBC

**Comment by LaneSh4d0w** [comment]
> SBC: https://iptv--iptv.repl.co/Arabic/SBC

I think it will only work for a few moments, since the token changes over time, no ?

**Comment by freearhey** [comment]
@Nintendocustom Added.

**Comment by link8k** [comment]
@Nintendocustom Do you have a tutorial on how you created the link? Thanks

**Comment by Nintendocustom** [comment]
I fixed Al Summaria too: https://iptv--iptv.repl.co/Arabic/Al_summaria
 There is no tutorial @link8k

**Comment by mo7ebb** [comment]
It's working perfectly fine so far, thank you 

Can you please do the other 3 channels ?

**Comment by m5arish** [comment]
also, logo link for SBC https://shashatcom.faulio.com/storage/mediagallery/f3/12/small_6aacb64b11bd07aa726b64ea478a15f7690bb830.png

**Comment by LaneSh4d0w** [comment]
@link8k I think he just created a JS script that exactly does what you meant with the curl command + in the best of states, reloads the API link + playlist every 15/30 mins.

**Comment by mo7ebb** [comment]
> @link8k I think he just created a JS script that exactly does what you meant with the curl command + in the best of states, reloads the API link + playlist every 15/30 mins.
> 
> 
> 
> Indicative thing is the repl.co (repl.it) link, which is an online IDE, used by many to store and run code online.

I tried to do it with no luck

**Comment by jad222** [comment]
@link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
user enter https://shashatcom.faulio.com/api/v1/channels/ + 1 or 2 or 3 ......
`const express = require("express");
const request = require("request");
const app = express();
app.get("/", function (req, res) {
  let channel = req.query.ch;

  let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;

  request(urlTest, function (error, response) {
    if (!error) {
      var obj = JSON.parse(response.body);
      res.redirect(obj.streams.hls)
    }
  });
});
app.listen("8080");
module.exports = app;
`

**Comment by LaneSh4d0w** [comment]
> @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> user enter https://shashatcom.faulio.com/api/v1/channels/ + 1 or 2 or 3 ......
> ```
> const express = require("express");
> const request = require("request");
> const app = express();
> app.get("/", function (req, res) {
>   let channel = req.query.ch;
> 
>   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> 
>   request(urlTest, function (error, response) {
>     if (!error) {
>       var obj = JSON.parse(response.body);
>       res.redirect(obj.streams.hls)
>     }
>   });
> });
> app.listen("8080");
> module.exports = app;
> 
> ```

I'm going to take a look once i'm home :)

**Comment by LaneSh4d0w** [comment]
> 
> 
> @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> user enter https://shashatcom.faulio.com/api/v1/channels?ch= '1 or 2 or 3 ......'
> 
> ```
> const express = require("express");
> const request = require("request");
> const app = express();
> app.get("/", function (req, res) {
>   let channel = req.query.ch;
> 
>   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> 
>   request(urlTest, function (error, response) {
>     if (!error) {
>       var obj = JSON.parse(response.body);
>       res.redirect(obj.streams.hls)
>     }
>   });
> });
> app.listen("8080");
> module.exports = app;
> ```

Here's a working code : `const express = require("express");
const fetch = require('node-fetch');
const app = express();

// to be filled with every channel in the order of the API, only for testing.
var channels = ["blank", 'SBC', 'KSA1'];

app.get("/stream", function (req, res) {

  const chosenChannel = channels.indexOf(req.query.ch);

  const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + chosenChannel;

  res.setHeader('Content-Type', 'application/vnd.apple.mpegurl; charset=utf-8');
  res.setHeader('Transfer-Encoding', 'chunked');

  fetch(urlTest)
    .then(response => response.json())
    .then(json => {
      res.redirect(json.streams.hls)
    })
});
app.get("/", function (req, res) {
    res.write('It works ! Welcome ;)');
});
app.listen("8080");
module.exports = app;`

Example : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=SBC

**Comment by mo7ebb** [comment]
> > 
> 
> > 
> 
> > @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> 
> > user enter https://shashatcom.faulio.com/api/v1/channels?ch= '1 or 2 or 3 ......'
> 
> > 
> 
> > ```
> 
> > const express = require("express");
> 
> > const request = require("request");
> 
> > const app = express();
> 
> > app.get("/", function (req, res) {
> 
> >   let channel = req.query.ch;
> 
> > 
> 
> >   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> 
> > 
> 
> >   request(urlTest, function (error, response) {
> 
> >     if (!error) {
> 
> >       var obj = JSON.parse(response.body);
> 
> >       res.redirect(obj.streams.hls)
> 
> >     }
> 
> >   });
> 
> > });
> 
> > app.listen("8080");
> 
> > module.exports = app;
> 
> > ```
> 
> 
> 
> @jad222, here's a working code : 
> 
> ```
> 
> const express = require("express");
> 
> const fetch = require('node-fetch');
> 
> const app = express();
> 
> 
> 
> var channels = ['blank'];
> 
> // get all channels
> 
> fetch("https://shashatcom.faulio.com/api/v1/channels/")
> 
>     .then(response=>response.json())
> 
>     .then(json => {
> 
>       for (title in json) {
> 
>       if (json.hasOwnProperty(title)) {
> 
>         channels.push(json[title].title);
> 
>       }
> 
>   }
> 
> })
> 
> 
> 
> app.get("/stream", function (req, res) {
> 
>   const chosenChannel = channels.indexOf(req.query.ch);
> 
> 
> 
>   const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + chosenChannel;
> 
> 
> 
>   res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');
> 
> 
> 
>   fetch(urlTest)
> 
>     .then(response => response.json())
> 
>     .then(json => {
> 
>       res.redirect(json.streams.hls)
> 
>     })
> 
> });
> 
> app.get("/", function (req, res) {
> 
>     res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
> 
> });
> 
> app.listen("8080");
> 
> module.exports = app;
> 
> ```
> 
> 
> 
> EDIT : Did what I said. Now just look at the index page to see all available streams in their API. Just copy and paste the channel you wanna watch on the channel, and enjoy !
> 
> 
> 
> Example : your_link.co/stream?ch=SBC

So I created an account at repl
Copied your code, changed "chosen channel" to "1" and it still didn't work !
I have zero coding experience, but I thought of giving it a shot

**Comment by LaneSh4d0w** [comment]
> > > 
> > 
> > > 
> > 
> > > @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> > 
> > > user enter https://shashatcom.faulio.com/api/v1/channels?ch= '1 or 2 or 3 ......'
> > 
> > > 
> > 
> > > ```
> > 
> > > const express = require("express");
> > 
> > > const request = require("request");
> > 
> > > const app = express();
> > 
> > > app.get("/", function (req, res) {
> > 
> > >   let channel = req.query.ch;
> > 
> > > 
> > 
> > >   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> > 
> > > 
> > 
> > >   request(urlTest, function (error, response) {
> > 
> > >     if (!error) {
> > 
> > >       var obj = JSON.parse(response.body);
> > 
> > >       res.redirect(obj.streams.hls)
> > 
> > >     }
> > 
> > >   });
> > 
> > > });
> > 
> > > app.listen("8080");
> > 
> > > module.exports = app;
> > 
> > > ```
> > 
> > 
> > 
> > @jad222, here's a working code : 
> > 
> > ```
> > 
> > const express = require("express");
> > 
> > const fetch = require('node-fetch');
> > 
> > const app = express();
> > 
> > 
> > 
> > var channels = ['blank'];
> > 
> > // get all channels
> > 
> > fetch("https://shashatcom.faulio.com/api/v1/channels/")
> > 
> >     .then(response=>response.json())
> > 
> >     .then(json => {
> > 
> >       for (title in json) {
> > 
> >       if (json.hasOwnProperty(title)) {
> > 
> >         channels.push(json[title].title);
> > 
> >       }
> > 
> >   }
> > 
> > })
> > 
> > 
> > 
> > app.get("/stream", function (req, res) {
> > 
> >   const chosenChannel = channels.indexOf(req.query.ch);
> > 
> > 
> > 
> >   const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + chosenChannel;
> > 
> > 
> > 
> >   res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');
> > 
> > 
> > 
> >   fetch(urlTest)
> > 
> >     .then(response => response.json())
> > 
> >     .then(json => {
> > 
> >       res.redirect(json.streams.hls)
> > 
> >     })
> > 
> > });
> > 
> > app.get("/", function (req, res) {
> > 
> >     res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
> > 
> > });
> > 
> > app.listen("8080");
> > 
> > module.exports = app;
> > 
> > ```
> > 
> > 
> > 
> > EDIT : Did what I said. Now just look at the index page to see all available streams in their API. Just copy and paste the channel you wanna watch on the channel, and enjoy !
> > 
> > 
> > 
> > Example : your_link.co/stream?ch=SBC
> 
> So I created an account at repl
> Copied your code, changed "chosen channel" to "1" and it still didn't work !
> I have zero coding experience, but I thought of giving it a shot 

With this code, you should have put the channel name, not the channel number :)

**Comment by mo7ebb** [comment]
So it should look like this ? 
It's still not working

const express = require("express");
const fetch = require('node-fetch');
const app = express();

var channels = ['blank'];
// get all channels
fetch("https://shashatcom.faulio.com/api/v1/channels/")
    .then(response=>response.json())
    .then(json => {
      for (title in json) {
      if (json.hasOwnProperty(title)) {
        channels.push(json[title].title);
      }
  }
})

app.get("/stream", function (req, res) {
  const chosenChannel = channels.indexOf(req.query.ch);

  const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + ksa1;

  res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');

  fetch(urlTest)
    .then(response => response.json())
    .then(json => {
      res.redirect(json.streams.hls)
    })
});
app.get("/", function (req, res) {
    res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
});
app.listen("8080");
module.exports = app;

**Comment by LaneSh4d0w** [comment]
> So it should look like this ? 
> It's still not working
> 
> const express = require("express");
> const fetch = require('node-fetch');
> const app = express();
> 
> var channels = ['blank'];
> // get all channels
> fetch("https://shashatcom.faulio.com/api/v1/channels/")
>     .then(response=>response.json())
>     .then(json => {
>       for (title in json) {
>       if (json.hasOwnProperty(title)) {
>         channels.push(json[title].title);
>       }
>   }
> })
> 
> app.get("/stream", function (req, res) {
>   const chosenChannel = channels.indexOf(req.query.ch);
> 
>   const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + ksa1;
> 
>   res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');
> 
>   fetch(urlTest)
>     .then(response => response.json())
>     .then(json => {
>       res.redirect(json.streams.hls)
>     })
> });
> app.get("/", function (req, res) {
>     res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
> });
> app.listen("8080");
> module.exports = app;

No, simply keep the code as is, load Node.js with this file in, go to your favorite browser, and load the main page. From there you will see all available channels. Just take one, add /stream?ch= and here add the channel name, not the ID. The program will take the ID automatically.

**Comment by Omario64** [comment]
> > @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> > user enter https://shashatcom.faulio.com/api/v1/channels?ch= '1 or 2 or 3 ......'
> > ```
> > const express = require("express");
> > const request = require("request");
> > const app = express();
> > app.get("/", function (req, res) {
> >   let channel = req.query.ch;
> > 
> >   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> > 
> >   request(urlTest, function (error, response) {
> >     if (!error) {
> >       var obj = JSON.parse(response.body);
> >       res.redirect(obj.streams.hls)
> >     }
> >   });
> > });
> > app.listen("8080");
> > module.exports = app;
> > ```
> 
> @jad222, here's a working code :
> 
> ```
> const express = require("express");
> const fetch = require('node-fetch');
> const app = express();
> 
> var channels = ['blank'];
> // get all channels
> fetch("https://shashatcom.faulio.com/api/v1/channels/")
>     .then(response=>response.json())
>     .then(json => {
>       for (title in json) {
>       if (json.hasOwnProperty(title)) {
>         channels.push(json[title].title);
>       }
>   }
> })
> 
> app.get("/stream", function (req, res) {
>   const chosenChannel = channels.indexOf(req.query.ch);
> 
>   const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + chosenChannel;
> 
>   res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');
> 
>   fetch(urlTest)
>     .then(response => response.json())
>     .then(json => {
>       res.redirect(json.streams.hls)
>     })
> });
> app.get("/", function (req, res) {
>     res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
> });
> app.listen("8080");
> module.exports = app;
> ```
> 
> EDIT : Did what I said. Now just look at the index page to see all available streams in their API. Just copy and paste the channel you wanna watch on the channel, and enjoy !
> 
> Example : your_link.co/stream?ch=SBC

@LaneSh4d0w  **you missed res.end(); after res.write :)**

**Comment by LaneSh4d0w** [comment]
> > > @link8k @LaneSh4d0w @mo7ebb i tried but needs more work, just simple example:
> > > user enter https://shashatcom.faulio.com/api/v1/channels?ch= '1 or 2 or 3 ......'
> > > ```
> > > const express = require("express");
> > > const request = require("request");
> > > const app = express();
> > > app.get("/", function (req, res) {
> > >   let channel = req.query.ch;
> > > 
> > >   let urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + channel;
> > > 
> > >   request(urlTest, function (error, response) {
> > >     if (!error) {
> > >       var obj = JSON.parse(response.body);
> > >       res.redirect(obj.streams.hls)
> > >     }
> > >   });
> > > });
> > > app.listen("8080");
> > > module.exports = app;
> > > ```
> > 
> > 
> > @jad222, here's a working code :
> > ```
> > const express = require("express");
> > const fetch = require('node-fetch');
> > const app = express();
> > 
> > var channels = ['blank'];
> > // get all channels
> > fetch("https://shashatcom.faulio.com/api/v1/channels/")
> >     .then(response=>response.json())
> >     .then(json => {
> >       for (title in json) {
> >       if (json.hasOwnProperty(title)) {
> >         channels.push(json[title].title);
> >       }
> >   }
> > })
> > 
> > app.get("/stream", function (req, res) {
> >   const chosenChannel = channels.indexOf(req.query.ch);
> > 
> >   const urlTest = "https://shashatcom.faulio.com/api/v1/channels/" + chosenChannel;
> > 
> >   res.setHeader('Content-Type', 'application/vnd.apple.mpegurl;');
> > 
> >   fetch(urlTest)
> >     .then(response => response.json())
> >     .then(json => {
> >       res.redirect(json.streams.hls)
> >     })
> > });
> > app.get("/", function (req, res) {
> >     res.write('Available channels : ' + channels.slice(1) + ". LaneSh4d0w 2021");
> > ```
> 
> res.end();
> 
> > });
> > app.listen("8080");
> > module.exports = app;
> > ```
> > 
> > EDIT : Did what I said. Now just look at the index page to see all available streams in their API. Just copy and paste the channel you wanna watch on the channel, and enjoy !
> > 
> > Example : your_link.co/stream?ch=SBC
> > ```
> 
> @LaneSh4d0w **you missed res.end(); after res.write :)**

Nice find, indeed :)

**Comment by Nintendocustom** [comment]
If you give me a language, channel name and the website with the stream or an explanation how it works, I will add it.

**Comment by mo7ebb** [comment]
> If you give me a language, channel name and the website with the stream or an explanation how it works, I will add it.

If you can creat links for the other 3 channels, that would be awesome 

All live streams are available on their official website 

https://www.shashatcom.sa/en/channel

**Comment by LaneSh4d0w** [comment]
Here you go people.

SBC : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=SBC
KSA 1 : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9%20%D9%A1
KSA Quran : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=%D8%A7%D9%84%D9%82%D8%B1%D8%A7%D9%86%20%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85
Ikhbariya : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=%D8%A7%D9%84%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1%D9%8A%D8%A9
Zikhayat : https://mysteriousdecisivedevelopments.lanesh4d0w.repl.co/stream?ch=%D8%B0%D9%83%D8%B1%D9%8A%D8%A7%D8%AA

**Comment by Nintendocustom** [comment]
- Ekhbariyah:  https://iptv--iptv.repl.co/Arabic/Ekhbariyah/
- Quran TV: https://iptv--iptv.repl.co/Arabic/Quran_TV/
- Saudi1 TV: https://iptv--iptv.repl.co/Arabic/Saudi1_TV/
- Sunnah TV: https://iptv--iptv.repl.co/Arabic/Sunnah_TV/
- Zikrayat: https://iptv--iptv.repl.co/Arabic/Zikrayat/

**Comment by m5arish** [comment]
> * Ekhbariyah:  https://iptv--iptv.repl.co/Arabic/Ekhbariyah/
> * Quran TV: https://iptv--iptv.repl.co/Arabic/Quran_TV/
> * Saudi1 TV: https://iptv--iptv.repl.co/Arabic/Saudi1_TV/
> * Sunnah TV: https://iptv--iptv.repl.co/Arabic/Sunnah_TV/
> * Zikrayat: https://iptv--iptv.repl.co/Arabic/Zikrayat/

Thank you 

@freearhey if you can please add it to the playlist, and heres the logos links

SBC 
https://shashatcom.faulio.com/storage/mediagallery/f3/12/small_6aacb64b11bd07aa726b64ea478a15f7690bb830.png

Ekhbariyah https://shashatcom.faulio.com/storage/mediagallery/4b/2b/small_93b2b7a11f66881821daaa94c6f8a6e345916ce5.PNG

Saudi 1
https://shashatcom.faulio.com/storage/mediagallery/98/c0/small_73d0446ff71096d59a7e95ad79a15b1cdf6d75f4.png

Zikrayat
https://shashatcom.faulio.com/storage/mediagallery/e8/2a/small_fa35007cc55fd94e6d420699e5ce2e4ac7236448.png

Quran TV
https://shashatcom.faulio.com/storage/mediagallery/67/fe/small_bf2974aa110f1cb0b912c16df45dd1b3641579c3.png

Sunnah TV
https://shashatcom.faulio.com/storage/mediagallery/74/7e/small_77cd28559f3b9cb650e13898b7097c7cd513679d.png

**Comment by freearhey** [comment]
Done.
