### ISSUE TITLE
Peru Request Channels

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#3063]
List of requests for Peru channels from other issues:

- [ ] [Auténtica TV](https://autenticatv.pe/) (Tarapoto) (#2948)
- [ ] [Cadena TV Huancayo](https://www.cadenatv.com.pe/en-vivo/) (#2947)
- [ ] [Contacto Deportivo TV](https://moyobamba.com/contactodeportivo/) (#2993)
- [ ] [Vía Altomayo](https://www.viaaltomayotv.com/) (#2952)
- [ ] [VZTV](https://moyobamba.com/vztv/) (#2991)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by LaneSh4d0w** [comment]
Actually... @MapGuy11 is there any way you can use your proxy to make "requests with headers" ? That might be useful for this case.

All those channels are broadcasted using OpenCaster, and to work, you need to add the Origin header to "https://opencaster.com/"

**Comment by MapGuy11** [comment]
> Actually... @MapGuy11 is there any way you can use your proxy to make "requests with headers" ? That might be useful for this case.
> 
> All those channels are broadcasted using OpenCaster, and to work, you need to add the Origin header to "https://www.opencaster.com/"

Let me see what I can spin up!

**Comment by MapGuy11** [comment]
@LaneSh4d0w I have been wrapping my brain around it do you know how to add the required headers to nginx? The redirect works but I can seem to get the headers to say it is coming from opencaster.com

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w I have been wrapping my brain around it do you know how to add the required headers to nginx? The redirect works but I can seem to get the headers to say it is coming from opencaster.com

Well, depends on what you say by "it works", because if it redirects correctly to the m3u8 file it's working, however if it goes to some sort of strange "gisslive" website then it's not.

Maybe if you simply make a request with headers, without redirection, maybe that'll work. However, we'll need to make sure that the content is safely readable by VLC or an alternative player.

**Comment by MapGuy11** [comment]
@LaneSh4d0w It has been redirecting to the gisslive website I have to fiddle with CORS and headers :( sigh.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w It has been redirecting to the gisslive website I have to fiddle with CORS and headers :( sigh.

Yeah, I had tried too, but it's a pain in the *** to make it work properly. I had the m3u8 file loaded in a text buffer from node-fetch... x)

**Comment by sguinetti** [comment]
I find other channel with opencaster link: https://moyobamba.com/tv5soritor/

**Comment by LaneSh4d0w** [comment]
Did someone try the EXTVLCOPT method ?

**Comment by LaneSh4d0w** [comment]
Ah, Authentica changed server, it's now https://live.obslivestream.com:1936/autenticatv/ngrp:autenticatv_all/playlist.m3u8

**Comment by sguinetti** [comment]
> Ah, Authentica changed server, it's now https://live.obslivestream.com:1936/autenticatv/ngrp:autenticatv_all/playlist.m3u8 . Right now it's streaming Caracol ?

I was checking this link and Caracol is not broadcasting. I guess it is a syndication program.

**Comment by LaneSh4d0w** [comment]
Yes, it was streaming a program from Caracol, inside their channel. Maybe
it's a specific TV Show

**Comment by LaneSh4d0w** [comment]
Via Altomayo : https://live.obslivestream.com:1936/viaaltomayo/ngrp:viaaltomayo_all/playlist.m3u8 (referrer locked to https://bradmax.com/

**Comment by Dum4G** [comment]
> Via Altomayo : https://live.obslivestream.com:1936/viaaltomayo/ngrp:viaaltomayo_all/playlist.m3u8

404

**Comment by LaneSh4d0w** [comment]
> > Via Altomayo : https://live.obslivestream.com:1936/viaaltomayo/ngrp:viaaltomayo_all/playlist.m3u8
> 
> 404

That was from their original website when I tried to look at it. Might be not 24/7

**Comment by sguinetti** [comment]
> > > Via Altomayo : https://live.obslivestream.com:1936/viaaltomayo/ngrp:viaaltomayo_all/playlist.m3u8
> > 
> > 
> > 404
> 
> That was from their original website when I tried to look at it. Might be not 24/7

Now is: https://live.obslivestream.com/viaaltomayomux/index.m3u8

**Comment by sguinetti** [comment]
> Contacto Deportivo : https://live.obslivestream.com:1936/cdeportivo/ngrp:cdeportivo_all/playlist.m3u8

Now is: https://live.obslivestream.com/cdeportivomux/index.m3u8
