### ISSUE TITLE
US Request Channels

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#3145]
List of requests for US channels from other issues:

- [ ] ABC Columbia (WOLO-TV) (#543)
- [ ] ABC7 New York (WABC-TV) (#748, #1587)
- [ ] ABC11 WTVD (#543)
- [ ] ABC13 Houston (KTRK-TV) (#543)
- [ ] ABC Spark (#746)
- [ ] AMC Brasil (#2293)
- [ ] AMC Romania (#762)
- [x] AXN (#1599)
- [ ] AXN Brazil (#2293)
- [ ] AXN Polska (https://github.com/iptv-org/iptv/issues/1965#issuecomment-799695246)
- [x] Boomerang (#738)
- [ ] Cartoon Network Asia (#1605, #2997)
- [ ] Cartoon Network Brasil (#2293)
- [ ] Cartoon Network East (#737, #1714)
- [ ] Cartoon Network India (#854)
- [ ] Cartoon Network Pakistan (#1608)
- [ ] Cartoon Network Polska (https://github.com/iptv-org/iptv/issues/1965#issuecomment-799695246)
- [ ] Cartoon Network UK (#1714)
- [ ] Cartoon Network West (#737, #1714)
- [x] Cartoonito Italia (added via https://github.com/iptv-org/iptv/commit/dd63749b655741914588571d17d45db9f3f45a9c)
- [ ] CBS 17 (WNCN) (#543)
- [x] CBS 2 New York (WCBS-TV) (#748) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] CBS Chicago (WBBM-TV) (#2214)
- [x] CBS Dallas (KTVT) (#543) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [x] Cinemax (#543) (added via #1962)
- [ ] CMT Canada (#745)
- [x] CNBC Europe (#1878)
- [ ] CNN International South Asia (#1608, #1599)
- [ ] CNN USA (in SD quality) (#1546)
- [ ] Crime & Investigation Asia (#1599)
- [ ] Crime & Investigation Canada (#745)
- [ ] Crime & Investigation UK (#1379)
- [ ] Crime & Investigation USA (#1379)
- [ ] Comedy Central East (#1599)
- [ ] Comedy Central West (#1599)
- [ ] Disney Channel Asia (#1714, #1599, #2980)
- [ ] Disney Channel Canada (#745, #746)
- [ ] Disney Channel East (#746, #1256, #1714, #1913, #1599)
- [ ] Disney Channel India (#709, #854)
- [ ] Disney Channel Romania (#762)
- [ ] Disney Channel West (#746, #1256, #1714, #1913, #1599)
- [x] ~~Disney Channel UK (#1714)~~ (channel was [closed](https://en.wikipedia.org/wiki/Disney_Channel_(British_and_Irish_TV_channel)))
- [ ] Disney Junior Canada (#745, #746)
- [ ] Disney Junior East (#746, #1599)
- [ ] Disney Junior West (#746, #1599)
- [ ] Disney La Chaîne (#745)
- [ ] Disney XD Canada (#745, #746)
- [ ] Disney XD East (#746, #1913, #1599)
- [ ] Disney XD West (#746, #1913, #1599)
- [x] ~~DMAX (#2173)~~ (removed due to https://github.com/iptv-org/iptv/issues/1831)
- [ ] Fight Network (#1380)
- [x] ~~Food Network Italia (#2173)~~ (removed due to https://github.com/iptv-org/iptv/issues/1831)
- [x] Fox News (#1586) (added via #1954)
- [ ] Fox East (#1587, #1599)
- [ ] Fox 4 Dallas-Fort Worth (KDFW) (#543)
- [ ] Fox 5 Atlanta (WAGA-TV) (#543)
- [ ] Fox 8 News (WJW) (#543)
- [ ] Fox 13 Tampa Bay (WTVT) (#543)
- [ ] Fox Action Movies (#1599)
- [ ] Fox Carolina (WHNS) (#543)
- [ ] [Fox Family Movies](https://en.wikipedia.org/wiki/Fox_Family_Movies) (#1599)
- [ ] Fox League 502 (#2341)
- [ ] [Fox Movies](https://en.wikipedia.org/wiki/Fox_Movies_(Southeast_Asian_TV_channel)) (#1118)
- [ ] Fox Sports Brasil (#2293)
- [x] Fox Sports 2 Asia (#1599) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [x] Fox Sports 3 Asia (#1599) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] Golf Channel Malaysia (#1599)
- [ ] GSN (Game Show Network) (#1587)
- [x] HBO (#1118) (added via #1962)
- [ ] HBO Brasil (#2293)
- [x] HBO Malaysia (#1599) (added via https://github.com/iptv-org/iptv/commit/edfd20affd27ed10ec66de83b2f817bcb7378041)
- [ ] HBO Romania (#762)
- [x] ~~HGTV (Home & Garden) (#2173)~~ (removed due to https://github.com/iptv-org/iptv/issues/1831)
- [ ] Historia (#745)
- [ ] History 2 Canada (#745)
- [ ] History Canada (#745)
- [ ] History East (#1599)
- [x] History România (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [ ] History West (#1599)
- [ ] History TV 18 (#1608)
- [x] KCAL 9 (KCAL-TV) (#479) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] Lifetime Canada (#745)
- [ ] Marvel HQ (#854, #2316)
- [ ] MTV India (#1621)
- [ ] MTV Polska (https://github.com/iptv-org/iptv/issues/1965#issuecomment-799695246)
- [ ] MTV South East Asia (#1599)
- [ ] Nat Geo People (#1714, #1599)
- [ ] National Geographic Asia (#1379, #1599)
- [ ] National Geographic Canada (#745)
- [ ] National Geographic East (#1714)
- [x] National Geographic România (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [ ] National Geographic West (#1714)
- [ ] National Geographic Wild Canada (#745)
- [x] National Geographic Wild Romania (#762) (added via 87d2899c148f283a4669c0284ba95677b872ec4c)
- [ ] National Geographic Wild UK (#1714)
- [ ] National Geographic UK (#871, #1714)
- [ ] NBA TV (#1380)
- [ ] NBA TV Philippines (#2490)
- [x] NBC 4 New York (WNBC) (#748) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] NBC 5 Dallas-Fort Worth (KXAS-TV) (#543)
- [x] NBC 6 South Florida (WTVJ) (#543) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] NFL Network (#1380)
- [ ] Nick@Nite (#740)
- [ ] Nick Jr. (#740)
- [ ] Nick Jr. Asia (#1599)
- [ ] Nick Jr. România (#762)
- [ ] Nick Jr. UK (#2776)
- [ ] Nickelodeon Canada (#742)
- [ ] Nickelodeon East (#1714, #1599)
- [ ] Nickelodeon India (#1565)
- [ ] Nickelodeon Polska (https://github.com/iptv-org/iptv/issues/1965#issuecomment-799695246)
- [ ] Nickelodeon România (#762)
- [ ] Nickelodeon UK (#1714)
- [ ] Nickelodeon West (#1714, #1599)
- [ ] NickMusic (#740)
- [ ] Nicktoons (#740)
- [ ] Oh! K (#1599)
- [ ] Pac-12 Networks (#1380)
- [ ] Paramount Channel Romania (#762)
- [ ] Paramount Network Italia (#2173)
- [x] QVC Italia (#2173) (added via https://github.com/iptv-org/iptv/commit/c35c48d5b125001b3eb4a22a450ed69140e1e10e)
- [ ] SEC Network (#1380)
- [x] Showtime (#543, #1118) (added via #1962)
- [ ] Sonic Nickelodeon (#1565)
- [ ] Sony Channel Brasil (#2293)
- [x] Starz (#479, #543) (added via #1962)
- [ ] Sundance (#543)
- [ ] Syfy Brasil (#2293)
- [ ] TeenNick (#740)
- [x] The CW (#1397) (added via #1954)
- [ ] [The Food Channel](https://foodchannel.com/) (#1377)
- [ ] TNT Romania (#762)
- [ ] WAFB 9 News (#543)
- [ ] Warner TV Southeast Asia (#1599)
- [ ] WGN-TV (#2384)
- [ ] WIS News 10 (#543)
- [ ] WNET (#748)
- [x] WPLG Local 10 (#543) (added via https://github.com/iptv-org/iptv/commit/dc62ca8d2425f395a7fa6046bb4f98c371b1be0e)
- [ ] WRAL-TV (#543)
- [ ] WWE Network (#1380, #1599, #2434)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by caten0** [comment]
I want primo tv.
Here is a official website :https://www.primotv.com/

**Comment by CHJ85** [comment]
Just a quick FYI. You might wanna go over your channels list soon as most of the Disney owned channels will be shutting down worldwide this year.
https://whatsondisneyplus.com/disney-to-close-100-tv-channels-in-2021/

All of Asia will be purged from October 1st: https://insidethemagic.net/2021/04/disney-plus-shutdown-disney-channels-jp1/
These being: Disney Channel and Disney Junior, Fox, Fox Crime, Fox Life, FX, Fox Movies, Fox Action Movies, Fox Family Movies, Fox Sports, Fox Sports 2, Fox Sports 3, Nat Geo People, Star Movies China, SCM Legend, Star Sports 1, Star Sports 2, Channel V

**Comment by Dum4G** [comment]
> Just a quick FYI. You might wanna go over your channels list soon as most of the Disney owned channels will be shutting down worldwide this year.

Don't you worry. We'll have them until they're broadcasting. All of them will eventually be removed by bot when the fun ends

**Comment by fotvnetwork** [comment]
Biz TV (new link):
http://gideommd.mmdlive.lldns.net/gideommd/46c072b287224782a4d4ce93c3646589/manifest.m3u8

**Comment by jkemp814** [comment]
Checked off: ABC7 New York (WABC-TV)

**Comment by jkemp814** [comment]
NBA TV is no longer in the U.S. list? It shows under the us.m3u, but not in Kodi or VLC. 

Line: 2704 - tvg-country="TH"

**Comment by BeesKnees09** [comment]
Longhorns Network would be awesome guy!
