### ISSUE TITLE
Indonesia Request Channels

### ISSUE THREAD

**Issue by Jodi910** [iptv-org/iptv#4794]
List of requests for INDONESIA channels from other issues:

- [ ] ANTV

- [ ] Badar

- [ ] BBStv

- [ ] DAAitv

- [ ] GTV (https://github.com/iptv-org/iptv/issues/4649#issue-1002651674) Broken stream

- [ ] Indosiar

- [ ] INews (https://github.com/iptv-org/iptv/issues/4649#issue-1002651674) Broken stream

- [ ] Inspiratv

- [ ] JPM

- [ ] Kompas

- [ ] MagnaHD

- [ ] Metro TV (Broken stream)

- [ ] Metro globe network

- [ ] MNCTV (https://github.com/iptv-org/iptv/issues/4649#issue-1002651674) Broken stream

- [ ] mytv

- [ ] NET.

- [ ] Nusantara

- [ ] Ochannel

- [ ] RCTI (https://github.com/iptv-org/iptv/issues/4649#issue-1002651674) Broken stream

- [ ] RTV

- [ ] SCTV

- [ ] Trans7

- [ ] TVmu

- [ ] tvOne

- [ ] UGTV

And please add more Indonesia subtitle channel like ;

- [ ] AXN

- [ ] Cartoon Network

- [ ] Cinemax

- [ ] HBO Original (like "Malaysia") but with Indonesia subtitle

- [ ] Nickelodeon

- [ ] tvN

- [ ] Warner Tv

Maybe there still have more Indonesia subtitle channel that i know or dont know 

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by Jodi910** [comment]
**Channel Name:** ANTV
**Website:** https://www.antvklik.com/
**Stream URL(optional):** https://www.visionplus.id/watch/channel/12/antv?cnumb=12
**Note:** The livestream on ANTV website not showing the content(video) so i take from another website

**Channel Name:** Badar
**Website:** https://www.badartv.co.id/
**Stream URL(optional):** https://www.badartv.co.id/live-tv-badar-tv/
**Note:** not 24 Hour /day

**Channel Name:** BBStv
**Website:** https://www.bbstv.id/
**Stream URL(optional):** http://streaming.bbstv.id/
**Note:** not 24 Hour /day

**Channel Name:** DAAitv
**Website:** https://www.daaitv.co.id/DAAI-WP/
**Stream URL(optional):** https://www.daaitv.co.id/DAAI-WP/live-streaming1/
**Note:** not 24 Hour /day

**Channel Name:** Indosiar
**Website:** https://www.indosiar.com/
**Stream URL(optional):** https://www.indosiar.com/#streaming

**Channel Name:** Inspira
**Website:** https://www.inspira.tv/
**Stream URL(optional):** https://www.inspira.tv/live
**Note:** not 24 Hour /day

**Channel Name:** JPM
**Website:** http://jpmtelevisi.com/
**Stream URL(optional):** https://www.jpmstream.com/mobile/1.html
**Note:** not 24 Hour /day

**Channel Name:** Kompastv
**Website:** https://www.kompas.tv/
**Stream URL(optional):** https://www.kompas.tv/live


**Channel Name:** Magna
**Stream URL(optional):** https://m.medcom.id/magnachannel
**Note:** not 24 Hour /day

**Channel Name:** Metro
**Stream URL(optional):** https://m.medcom.id/streaming

**Channel Name:** Metro Globe Network
**Stream URL(optional):** https://m.medcom.id/mgnetwork
**Note:** not 24 Hour /day

**Channel Name:** mytv
**Website:** https://www.mytv.co.id/
**Stream URL(optional):** https://www.mytv.co.id/mytv-live
**Note:** maybe they Stream URL not gonna work .try from Third website . _not 24 Hour /day_

**Channel Name:** NET.
**Website:** https://www.netmedia.co.id/
**Stream URL(optional):** https://www.netmedia.co.id/live-streaming

**Channel Name:** Nusantara
**Website:** https://nusantaratv.com

**Channel Name:** Ochannel
**Website:** https://www.ochanneltv.com/
**Stream URL(optional):** on Home page

**Channel Name:** RTV
**Website:** https://www.rtv.co.id/

**Channel Name:** SCTV
**Website:** https://www.sctv.co.id/
**Stream URL(optional):** https://www.sctv.co.id/live-streaming

**Channel Name:** Trans 7 
**Website:** https://www.trans7.co.id/
**Stream URL(optional):** https://www.trans7.co.id/live-streaming

**Channel Name:** tvmu
**Website:** https://tvmu.tv/

**Channel Name:** tvOne
**Website:** https://www.tvonenews.com/
**Stream URL(optional):** https://www.tvonenews.com/live

**Channel Name:** UGTV
**Website:** https://ugtv.co.id/
**Stream URL(optional):** https://ugtv.co.id/home/live-streaming/


Here more livestream channel from third website 

- https://m.vidio.com/
- https://www.visionplus.id/
- https://www.useetv.com/
- https://www.mncvision.id
- https://jpmstream.com

**Note:** Maybe there have more source or something

**Comment by Sphinxroot** [comment]
ANTV
https://liveanevia.mncnow.id/live/eds/ANTV/sa_dash_vmx/ANTV.mpd + DMR KEY

Badar
https://e1.siar.us/badartv/live/playlist.m3u8  (1080p)

BBStv
http://103.119.54.246:8080/hls/bbstv.m3u8 (720p)

DAAitv
https://dcunilive7-lh.akamaihd.net/i/dclive_1@135498/master.m3u8 +Token   need to be Streamlinked

Indosiar
Stream Is tokenized from site
remplacement https://akamai.mncnow.id/live/eds/INDOSIAR-ryzen/sa_dash/INDOSIAR-ryzen.mpd

Inspira
https://v2.siar.us/inspiratv/live/playlist.m3u8 (720p)

JPM
http://122.248.43.138:1935/jpm/myStream/playlist.m3u8 No Mediamanifest found


Kompastv
No Stream was on
dailymotion give private

Magna
https://edge.medcom.id/live-edge/smil:magna.smil/playlist.m3u8 (1080p)

Metro
https://www.dailymotion.com/video/x75p70w  i get private video
but this work
https://stream-02.nyc.dailymotion.com/sec(CFYS0CyzC0phI1myd5MCSxDq6dLOq10xc7jXmsc3sac)/dm/3/x75p70w/d/live-3.m3u8

Metro Globe Network
https://edge.medcom.id/live-edge/smil:mgnch.smil/playlist.m3u8 (1080p)

mytv
Under Maintenance

NET.
https://www.youtube.com/channel/UC1-ATnDVEwKT6-0aEeJ2ibA/live

Nusantara
https://v6.siar.us/nusantaratv/live/playlist.m3u8 (720p)

Ochannel
Token Stream

RTV
No Live Found

SCTV
MPD DASH + Token

Trans 7
Geo Stream

tvmu
rtmp://118.97.183.222:1935/discover/muhammadiyahtv From Source Code  , but player empty

tvOne
https://www.youtube.com/watch?v=JzLDCNxTEmA
https://www.youtube.com/channel/UCER4rvDnRBPr_ncYW4UCZjg/live  return to channel list non working

UGTV
https://cdn.gunadarma.ac.id/streams/ugtv/ingestugtv.m3u8 (720p)

**Comment by furlunaga** [comment]
TV9 Nusantara
https://www.useetv.com/livetv/tv9
http://tv9.co.id/stream
TVEdukasi
http://tve.kemdikbud.go.id/
RTV
https://www.useetv.com/livetv/rtv
NET Mediatama
https://www.useetv.com/livetv/net

**Comment by furlunaga** [comment]
https://m.vidio.com/live/875-net-tv
https://m.vidio.com/live/1561-rtv
https://www.aswajatv.com/

**Comment by F640** [comment]
> Here more livestream channel from third website
> 
> - https://m.vidio.com/
> - https://www.visionplus.id/
> - https://www.useetv.com/
> - https://www.mncvision.id
> - https://jpmstream.com

Additional 3rd party livestream channel sources:
- https://www.mivo.com/ (tokenized)
- https://youtv.live/ (needs user agent spoofing and geo-blocked)
- [Kugo](https://www.kugosky.tv/) (app only for now)
- https://maxstream.tv/ (geo-blocked and some channel has DRM)
- http://dens.tv/ (geo-blocked and http only)
- http://www.biznetvideo.net/ (http only)

Some information for quoted channel:
- Vidio: Tokenized, i heard they also start implementing DRM for some channels in this site
- Vision+: DRM'ed
- UseeTV: Tokenized
- MNC Vision: You probably mean Vision+
- JPM Stream: http stream but this site insists user to use https site instead http
